<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TripsAuditLogTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('trips_audit_log')->insert([
            [
                'id' => 1,
                'primary_id' => 1,
                'org_code' => 1001,
                'driver_id' => '550e8400-e29b-41d4-a716-446655440001',
                'driver_name' => 'John Doe',
                'vehicle_id' => '550e8400-e29b-41d4-a716-446655440101',
                'vehicle_registration_number' => 'DHK-METRO-1234',
                'start_location' => 'Dhaka Office',
                'destination' => 'Chittagong Branch',
                'start_time' => Carbon::now()->subDays(2)->setHour(9)->setMinute(0),
                'end_time' => null,
                'distance_km' => null,
                'purpose' => 'Official Meeting',
                'fuel_cost' => 0.00,
                'total_cost' => 0.00,
                'is_locked' => 0,
                'status' => 'pending',
                'action' => 'create',
                'created_by' => 4,
                'created_at' => Carbon::now()->subDays(3),
            ],
            [
                'id' => 2,
                'primary_id' => 1,
                'org_code' => 1001,
                'driver_id' => '550e8400-e29b-41d4-a716-446655440001',
                'driver_name' => 'John Doe',
                'vehicle_id' => '550e8400-e29b-41d4-a716-446655440101',
                'vehicle_registration_number' => 'DHK-METRO-1234',
                'start_location' => 'Dhaka Office',
                'destination' => 'Chittagong Branch',
                'start_time' => Carbon::now()->subDays(2)->setHour(9)->setMinute(0),
                'end_time' => Carbon::now()->subDays(2)->setHour(15)->setMinute(30),
                'distance_km' => 264.50,
                'purpose' => 'Official Meeting',
                'fuel_cost' => 3500.00,
                'total_cost' => 4200.00,
                'is_locked' => 1,
                'status' => 'completed',
                'action' => 'modify',
                'created_by' => 4,
                'created_at' => Carbon::now()->subDays(2)->setHour(16),
            ],
            [
                'id' => 3,
                'primary_id' => 2,
                'org_code' => 1001,
                'driver_id' => '550e8400-e29b-41d4-a716-446655440002',
                'driver_name' => 'Jane Smith',
                'vehicle_id' => '550e8400-e29b-41d4-a716-446655440102',
                'vehicle_registration_number' => 'DHK-GA-5678',
                'start_location' => 'Head Office',
                'destination' => 'Sylhet Office',
                'start_time' => Carbon::now()->subDay()->setHour(8)->setMinute(0),
                'end_time' => null,
                'distance_km' => null,
                'purpose' => 'Document Delivery',
                'fuel_cost' => 0.00,
                'total_cost' => 0.00,
                'is_locked' => 0,
                'status' => 'pending',
                'action' => 'create',
                'created_by' => 5,
                'created_at' => Carbon::now()->subDays(2),
            ],
            [
                'id' => 4,
                'primary_id' => 3,
                'org_code' => 1002,
                'driver_id' => '550e8400-e29b-41d4-a716-446655440003',
                'driver_name' => 'Mike Johnson',
                'vehicle_id' => '550e8400-e29b-41d4-a716-446655440103',
                'vehicle_registration_number' => 'SYL-KA-2468',
                'start_location' => 'Sylhet Office',
                'destination' => 'Rajshahi Branch',
                'start_time' => Carbon::now()->subDays(5)->setHour(10)->setMinute(0),
                'end_time' => null,
                'distance_km' => null,
                'purpose' => 'Equipment Transport',
                'fuel_cost' => 0.00,
                'total_cost' => 0.00,
                'is_locked' => 0,
                'status' => 'pending',
                'action' => 'create',
                'created_by' => 6,
                'created_at' => Carbon::now()->subDays(6),
            ],
            [
                'id' => 5,
                'primary_id' => 4,
                'org_code' => 1001,
                'driver_id' => '550e8400-e29b-41d4-a716-446655440001',
                'driver_name' => 'John Doe',
                'vehicle_id' => '550e8400-e29b-41d4-a716-446655440103',
                'vehicle_registration_number' => 'CHT-HA-9101',
                'start_location' => 'Chittagong Port',
                'destination' => 'Dhaka Office',
                'start_time' => Carbon::now()->subDays(1)->setHour(14)->setMinute(0),
                'end_time' => null,
                'distance_km' => null,
                'purpose' => 'Cargo Pickup',
                'fuel_cost' => 0.00,
                'total_cost' => 0.00,
                'is_locked' => 0,
                'status' => 'pending',
                'action' => 'create',
                'created_by' => 4,
                'created_at' => Carbon::now()->subDays(2),
            ],
        ]);
    }
} 