version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transport-app
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - transport-network
    depends_on:
      - database
      - redis
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=transport_ms
      - DB_USERNAME=transport_user
      - DB_PASSWORD=transport_pass
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  database:
    image: mysql:8.0
    container_name: transport-database
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=transport_ms
      - MYSQL_USER=transport_user
      - MYSQL_PASSWORD=transport_pass
      - MYSQL_ROOT_PASSWORD=root_password
    networks:
      - transport-network
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: transport-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - transport-network
    command: redis-server --appendonly yes

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: transport-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root_password
    networks:
      - transport-network
    depends_on:
      - database

networks:
  transport-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
