version: '3.8'

services:
  # Keycloak (Authentication System)
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak_postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: secret
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    ports:
      - "8080:8080"
    depends_on:
      keycloak_postgres:
        condition: service_healthy
    networks:
      - vms_internal_net

  # RabbitMQ (Message Broker)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
    networks:
      - vms_internal_net

  # MySQL (For Laravel or PHP Microservices)
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ecommerce
    ports:
      - "7708:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - vms_internal_net

  # PostgreSQL (Used by Keycloak)
  keycloak_postgres:
    image: postgres:13
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: secret
    ports:
      - "7432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    networks:
      - vms_internal_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Kong Database (PostgreSQL)
  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "7433:5432"
    volumes:
      - ./volumes/kong-postgres:/var/lib/postgresql/data
    networks:
      - vms_internal_net

  # Kong API Gateway
  kong:
    image: kong:3.6
    container_name: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    depends_on:
      - kong-database
    networks:
      - vms_internal_net

networks:
  vms_internal_net:
    driver: bridge
